# Generated by Django 4.2.30 on 2026-07-07 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-80), django.core.validators.MaxValueValidator(80)])),
                ('perceived_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-80), django.core.validators.MaxValueValidator(80)])),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('rainfall_mm', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
